_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.10.12
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
actor_lr:
    value: 0.0003
batch_size:
    value: 512
config_file:
    value: ""
critic_lr:
    value: 0.0003
disable_training:
    value: false
disable_wandb:
    value: false
env:
    value: grid_world
eval_freq:
    value: 10000
eval_iterations:
    value: 100
gamma:
    value: 0.95
gradient_clip:
    value: 1
gradient_estimator:
    value: gst
gst_gap:
    value: 0.7
gumbel_temp:
    value: 1
hidden_dim_width:
    value: 64
just_demo_agents:
    value: false
log_grad_variance:
    value: false
log_grad_variance_interval:
    value: 1000
max_episode_length:
    value: 100
offline_wandb:
    value: false
policy_regulariser:
    value: 0.001
pretrained_agents:
    value: ""
rao_k:
    value: 1
render:
    value: false
replay_buffer_size:
    value: 200000
reward_per_agent:
    value: false
save_agents:
    value: false
seed:
    value: 0
soft_update_size:
    value: 0.01
standardise_rewards:
    value: false
tags_end:
    value: 0.5
tags_period:
    value: 2000000
tags_start:
    value: 5
total_steps:
    value: 200000
train_repeats:
    value: 5
user_name:
    value: aithalskanda66
wandb_project_name:
    value: maddpg-sink-project
warmup_episodes:
    value: 10
